### PR TITLE
Performance improvement spellSuggest

### PR DESCRIPTION
**Pull request by IlyaKirillov**
When checking the correct word if it is not correct, it is not required to do words suggestion.

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Thanks for the work , but I think you are misunderstanding what `spellSuggest` does. It actually is supposed to do the exact same thing as `spellSuggestions`, but only return the top word instead. This pull request would make it so that only `spellSuggestions` returns suggestions.

**Comment by IlyaKirillov** [comment]
This function return the top word, but in real it's queries all options. It spent a lot of time. Take for example MS Word. It check and emphasize the wrong word with out any suggestions. And only after the request it shows the substitution options. Check should be fast, but now on every checking request if the word is not correct, a request is made of all the options selection (only in order to give the top word)

**Comment by nathanjsweet** [comment]
Might I suggest creating a new function? It might be called `isCorrect` or something like that.

**Comment by IlyaKirillov** [comment]
That would be great. Thank you!

**Comment by nathanjsweet** [comment]
I've [opened an issue for it](https://github.com/nathanjsweet/nodehun/issues/25). However, my wife and I are expecting a child this month so it will be a while before I can get to it. If you want to do it yourself make sure to add to the documentation and to create an example in the [examples folder](https://github.com/nathanjsweet/nodehun/tree/master/examples).

**Pull request closed without merging**
