### PR TITLE
added support for Hunspell analyze() and generate()

### PR DESCRIPTION
**Pull request by ben-page**
I also replaced dictionaries with the ones from Libre Office. The previously included aff file didn't contain the required data for analyze() and generate() to do much. I added new examples and updated the documentation.

### CODE REVIEW

**Comment by ben-page** [comment]
I tested both pre and post 0.12

**Comment by nathanjsweet** [comment]
Wow! Thank you very much! I will try to merge this as soon as I can.

**Comment by nathanjsweet** [comment]
Easily the best commit I've ever received. I branched on my local machine, assuming I would have to update your style or make sure the readme was good, but you really nailed it. I'm only sorry it took me a week to merge. Thanks so much!

**Comment by ben-page** [comment]
Thanks! Glad that I could contribute.

**Comment by nathanjsweet** [comment]
Ben, would you be interested in taking over this project?

**Pull request merged**
